version: "3"

services:
  server:
    build:
      args:
        - target=dev
    restart: always
    ports:
      - 80:80
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
